### ISSUE TITLE
Set up RVC open project site

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/cryptode#255]
RVC looks like a very useful piece of software; shall we have an Open Project site set up for it after Nereon’s?

We could get getrvc.com for example. Once we know the domain, I can create the repo for the site.

**Comment by strogonoff** [comment]
(cc @ronaldtse)

**Comment by ronaldtse** [comment]
Great idea. In addition, perhaps it's time to rename RVC to something more brandable?

This is @opoudjis 's domain. I'd say the keywords of RVC are: "manage, protect secret communication tunnels"

**Comment by strogonoff** [comment]
@ronaldtse  We could be picky about the name… or not, depending on whether the scale of this initiative warrants it.

If your suggestion to rename RVC stems purely from domain unavailability, I’d point out that “getX.com” is a common workaround used by the likes of getpocket.com and many more (I believe it used to be getdropbox.com even, back in the days!)

**Comment by ronaldtse** [comment]
@strogonoff I have not forgotten this, I will revert with a name soon. 😉

**Comment by strogonoff** [comment]
Got it!

**Comment by ronaldtse** [comment]
So it's going to be cryptode.com

Cryptode: in Greek "crypt-" means hidden, "-ode" means path. So Cryptode protects you using a hidden path.

**Comment by strogonoff** [comment]
Setting up under https://github.com/riboseinc/cryptode.com

**Comment by strogonoff** [comment]
Note: site builds as of yesterday with the same Rakefile/.travis.yml as other OP sites, but I’m assuming CI for the cryptode.com repo is not yet set up elsewhere (Travis/AWS/GitHub) as the production domain is not available at the moment.

**Comment by ronaldtse** [comment]
@strogonoff as of now the repo doesn't have a `.travis.yml` file, so Travis can't run yet?

In any case the domain infra is not yet available; it will be a couple more days. I will update here.

**Comment by strogonoff** [comment]
@ronaldtse indeed, forgot to add .travis.yml, fixed now.

**Comment by ronaldtse** [comment]
Thanks @strogonoff , perhaps you could also add the typical README too?

**Comment by strogonoff** [comment]
sure, at least that doesn’t break the build 😉

**Comment by ronaldtse** [comment]
Ha! I was actually thinking of the Travis build link on the README 😉

**Comment by strogonoff** [comment]
Haha yeah a build could validate the README😂  If test specs are detailed enough, the README itself can even be inferred based on a template

I treat it as less of a priority in these cases since sites aren’t intended to be collaborated on as much as the actual software, but of course everything gets better with the [right] README

**Comment by ronaldtse** [comment]
Closing now.
